### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by 0x4c554c5a** [SingularisArt/Singularis#2]
hey there! How do I fix this error?
`remote: Repository not found.
fatal: repository 'https://github.com/SingularisArt/custom-snippets/' not found
fatal: clone of 'https://github.com/SingularisArt/custom-snippets' into submodule `

**Comment by SingularisArt** [comment]
Sorry for the late response. I just need to update the submodule because I changed the name of my custom snippets repo. It should be done by today.

If the error still persists by tomorrow, please re-open.
